import "./globals.css";

export const metadata = {
  title: "My Blog App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="flex flex-col items-center text-center" >
        <header className="text-4xl bg-amber-600 text-white w-full">Header</header>
        {children}
        <footer className="text-4xl bg-amber-500 text-white w-full">Footer</footer>
      </body>
      
    </html>
  );
}
